### ISSUE TITLE
一些类缺失

### ISSUE THREAD

**Issue by Small-BlueFish-hjy** [qifan777/uni-ai#1]
import io.qifan.server.menu.entity.MenuTable;
import io.qifan.server.menu.repository.MenuRepository;
import io.qifan.server.user.root.entity.User;
import io.qifan.server.user.root.entity.UserDraft;
import io.qifan.server.user.root.entity.dto.UserInfoInput;
import io.qifan.server.user.root.entity.dto.UserLoginInput;
import io.qifan.server.user.root.entity.dto.UserRegisterInput;
import io.qifan.server.user.root.entity.dto.UserResetPasswordInput;

**Comment by Small-BlueFish-hjy** [comment]
![image](https://github.com/qifan777/uni-ai/assets/93272135/60e0309e-eb55-472b-849b-c8d30523125d)

**Comment by qifan777** [comment]
需要编译一下，然后在target/generated-sources/annotations右键mark directory as/generated source root

**Comment by qifan777** [comment]
需要编译一下，然后在target/generated-sources/annotations右键mark directory as/generated source root
